import {Food} from './app/shared/models/Food';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Masala Dosa',
    cookTime: '10-20',
    price: 70,
    favorite: false,
    origins: ['India'],
    stars: 4.5,
    imageUrl: 'assets/Masala-Dosa.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id:'2',
    name: 'Falafal Wrap',
    price: 150,
    cookTime: '10',
    favorite: true,
    origins: ['middle east'],
    stars: 4.4,
    imageUrl: 'assets/healthy-falafel.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Veg Burger',
    price: 80,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us', 'india'],
    stars: 3.5,
    imageUrl: 'assets/maccas-burger.jpg',
    tags: ['FastFood', 'burger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 50,
    cookTime: '15-20',
    favorite: false,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/Fried-Potatoes.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Indian Thali',
    price: 500,
    cookTime: '40-50',
    favorite: true,
    origins: ['india', 'asia'],
    stars: 5.0,
    imageUrl: 'assets/Indian-Thali.jpg',
    tags: ['SlowFood', 'Full Meal', 'Dinner', 'Lunch'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 180,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/VegPizza.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]
